export const states: { [key: string]: string[] } = {
  'Andaman and Nicobar Islands': ['Port Blair'],
  'Andhra Pradesh': [
    'Adoni',
    'Amaravati',
    'Anantapur',
    'Chandragiri',
    'Chittoor',
    'Dowlaiswaram',
    'Eluru',
    'Guntur',
    'Kadapa',
    'Kakinada',
    'Kurnool',
    'Machilipatnam',
    'Nagarjunakonda',
    'Rajahmundry',
    'Srikakulam',
    'Tirupati',
    'Vijayawada',
    'Visakhapatnam',
    'Vizianagaram',
    'Yemmiganur'
  ],
  'Arunachal Pradesh': ['Itanagar'],
  Assam: [
    'Dhuburi',
    'Dibrugarh',
    'Dispur',
    'Guwahati',
    'Jorhat',
    'Nagaon',
    'Sivasagar',
    'Silchar',
    'Tezpur',
    'Tinsukia'
  ],
  Bihar: [
    'Ara',
    'Barauni',
    'Begusarai',
    'Bettiah',
    'Bhagalpur',
    'Bihar Sharif',
    'Bodh Gaya',
    'Buxar',
    'Chapra',
    'Darbhanga',
    'Dehri',
    'Dinapur Nizamat',
    'Gaya',
    'Hajipur',
    'Jamalpur',
    'Katihar',
    'Madhubani',
    'Motihari',
    'Munger',
    'Muzaffarpur',
    'Patna',
    'Purnia',
    'Pusa',
    'Saharsa',
    'Samastipur',
    'Sasaram',
    'Sitamarhi',
    'Siwan'
  ],
  Chandigarh: ['Chandigarh'],
  Chhattisgarh: [
    'Ambikapur',
    'Bhilai',
    'Bilaspur',
    'Dhamtari',
    'Durg',
    'Jagdalpur',
    'Raipur',
    'Rajnandgaon'
  ],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
  Delhi: ['Delhi', 'New Delhi'],
  Goa: ['Madgaon', 'Panaji'],
  Gujarat: [
    'Ahmadabad',
    'Amreli',
    'Bharuch',
    'Bhavnagar',
    'Bhuj',
    'Dwarka',
    'Gandhinagar',
    'Godhra',
    'Jamnagar',
    'Junagadh',
    'Kandla',
    'Khambhat',
    'Kheda',
    'Mahesana',
    'Morbi',
    'Nadiad',
    'Navsari',
    'Okha',
    'Palanpur',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Surat',
    'Surendranagar',
    'Valsad',
    'Veraval'
  ],
  Haryana: [
    'Ambala',
    'Bhiwani',
    'Chandigarh',
    'Faridabad',
    'Firozpur Jhirka',
    'Gurugram',
    'Hansi',
    'Hisar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Panipat',
    'Pehowa',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat'
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Dalhousie',
    'Dharmshala',
    'Hamirpur',
    'Kangra',
    'Kullu',
    'Mandi',
    'Nahan',
    'Shimla',
    'Una'
  ],
  'Jammu and Kashmir': [
    'Anantnag',
    'Baramula',
    'Doda',
    'Gulmarg',
    'Jammu',
    'Kathua',
    'Punch',
    'Rajouri',
    'Srinagar',
    'Udhampur'
  ],
  Jharkhand: [
    'Bokaro',
    'Chaibasa',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'Giridih',
    'Hazaribag',
    'Jamshedpur',
    'Jharia',
    'Rajmahal',
    'Ranchi',
    'Saraikela'
  ],
  Karnataka: [
    'Badami',
    'Ballari',
    'Bengaluru',
    'Belagavi',
    'Bhadravati',
    'Bidar',
    'Chikkamagaluru',
    'Chitradurga',
    'Davangere',
    'Halebid',
    'Hassan',
    'Hubballi-Dharwad',
    'Kalaburagi',
    'Kolar',
    'Madikeri',
    'Mandya',
    'Mangaluru',
    'Mysuru',
    'Raichur',
    'Shivamogga',
    'Shravanabelagola',
    'Shrirangapattana',
    'Tumakuru',
    'Vijayapura'
  ],
  Kerala: [
    'Alappuzha',
    'Vatakara',
    'Idukki',
    'Kannur',
    'Kochi',
    'Kollam',
    'Kottayam',
    'Kozhikode',
    'Mattancheri',
    'Palakkad',
    'Thalassery',
    'Thiruvananthapuram',
    'Thrissur'
  ],
  Ladakh: ['Kargil', 'Leh'],
  'Madhya Pradesh': [
    'Balaghat',
    'Barwani',
    'Betul',
    'Bharhut',
    'Bhind',
    'Bhojpur',
    'Bhopal',
    'Burhanpur',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dr. Ambedkar Nagar (Mhow)',
    'Guna',
    'Gwalior',
    'Hoshangabad',
    'Indore',
    'Itarsi',
    'Jabalpur',
    'Jhabua',
    'Khajuraho',
    'Khandwa',
    'Khargone',
    'Maheshwar',
    'Mandla',
    'Mandsaur',
    'Morena',
    'Murwara',
    'Narsimhapur',
    'Neemuch',
    'Nowgong',
    'Orchha',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Sarangpur',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Ujjain',
    'Vidisha'
  ],
  Maharashtra: [
    'Ahmadnagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Bhandara',
    'Bhusawal',
    'Bid',
    'Buldhana',
    'Chandrapur',
    'Daulatabad',
    'Dhule',
    'Jalgaon',
    'Kalyan',
    'Karli',
    'Kolhapur',
    'Mahabaleshwar',
    'Malegaon',
    'Matheran',
    'Mumbai',
    'Nagpur',
    'Nanded',
    'Nashik',
    'Osmanabad',
    'Pandharpur',
    'Parbhani',
    'Pune',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sevagram',
    'Solapur',
    'Thane',
    'Ulhasnagar',
    'Vasai-Virar',
    'Wardha',
    'Yavatmal'
  ],
  Manipur: ['Imphal'],
  Meghalaya: ['Cherrapunji', 'Shillong'],
  Mizoram: ['Aizawl', 'Lunglei'],
  Nagaland: ['Kohima', 'Mon', 'Phek', 'Wokha', 'Zunheboto'],
  Odisha: [
    'Balangir',
    'Baleshwar',
    'Baripada',
    'Bhubaneshwar',
    'Brahmapur',
    'Cuttack',
    'Dhenkanal',
    'Kendujhar',
    'Konark',
    'Koraput',
    'Paradip',
    'Phulabani',
    'Puri',
    'Sambalpur',
    'Udayagiri'
  ],
  Puducherry: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  Punjab: [
    'Amritsar',
    'Batala',
    'Chandigarh',
    'Faridkot',
    'Firozpur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Ludhiana',
    'Nabha',
    'Patiala',
    'Rupnagar',
    'Sangrur'
  ],
  Rajasthan: ['Jaipur', 'Jaisalmer', 'Jodhpur', 'Udaipur', 'Ajmer', 'Bikaner', 'Kota', 'Alwar'],
  Sikkim: ['Gangtok', 'Gyalshing', 'Lachung', 'Mangan'],
  'Tamil Nadu': ['Chennai', 'Madurai', 'Coimbatore', 'Tiruchirapalli'],
  Telangana: ['Hyderabad', 'Warangal'],
  Tripura: ['Agartala'],
  'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Agra', 'Varanasi'],
  Uttarakhand: ['Dehradun', 'Haridwar'],
  'West Bengal': ['Kolkata', 'Darjeeling', 'Siliguri']
};
